name: tractify
favicon: null
layout_spectrum: 0.6308064768090844
typography_spectrum: 0.6754408157430589
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.3137062434107065
  lightness: 0.5279142379295081
  saturation: 0.5562958407681435
  rhythmicContrast: 0.2283912543207407
purpose: []
